---
- hosts: localhost      # 接続先(localhostは、インベントリーになくとも指定可能)
  gather_facts: true
  become: yes
  vars:
    docker_users:
      - koichiro
    docker_edition: 'ce'
    docker_service_state: started
    docker_service_enabled: true
    docker_install_compose: true
  roles:
    - geerlingguy.docker
  tasks:

  - shell: hostname
    register: r_hostname
  - debug: { var: r_hostname.stdout }

  - debug: { var: ansible_connection }
  - debug: { var: ansible_playbook_python }
  - debug: { var: ansible_python_interpreter }
